### PR TITLE
Convert documentation to new format

### PR DESCRIPTION
**Pull request by ganto**
As I complained about the current state of the `debops.ferm` documentation in #57, I will make the start and converted the existing documentation to the "new" format. This should make it easier for everyone to add more content to the documentation of this very powerful Ansible role in the future.

### CODE REVIEW

**Comment by drybjed** [comment]
Excellent work, thank you! :-)

**Comment by ganto** [comment]
You're welcome. Is there anything that speaks against tagging the role? The documentation at http://docs.debops.org/en/latest/ansible/roles/debops.ferm.html is quite outdated.

**Comment by drybjed** [comment]
@ganto I think not... I'll check the code tommorow and maybe add some more examples, and tag it then.

**Comment by ganto** [comment]
Would be great. Thanks a lot!

**Pull request merged**
